apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: jenkins.pailor.com.ar
    http:
      paths:
      - backend:
          serviceName: jenkings-stable-jenkins
          servicePort: 8080
